/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  CurriculumData,  CurriculumRow,  DynamicFields,  ImageResult,  Message,  PdfKnowledge,  Resume,  VideoResult,  WebSearchResult,  WebSearchTool } from "../types"

import type * as types from "../types"
import type { partial_types }from "../partial_types";

export type StreamingServerTypes = {
  ExecuteWebSearch: WebSearchTool,
  ExtractCurriculumData: string,
  ExtractPdfKnowledge: string,
  ExtractResume: Resume,
  ProcessForm: DynamicFields,
  ProcessFormWithRAG: DynamicFields,
  SearchImages: ImageResult[],
  SearchVideos: VideoResult[],
}