/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";

import type {  DynamicFields,  ImageResult,  Message,  Resume,  VideoResult,  WebSearchResult,  WebSearchTool } from "../types"

import type * as types from "../types"

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "ExecuteWebSearch" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } message - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ExecuteWebSearch = async (
  message: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ExecuteWebSearch(
    message,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "ExtractResume" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } resume - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ExtractResume = async (
  resume: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ExtractResume(
    resume,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "ProcessForm" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } context_data - Input parameter.
 * @param { string } fields_data - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ProcessForm = async (
  context_data: string,
  fields_data: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ProcessForm(
    context_data,
    fields_data,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "SearchImages" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } message - Input parameter.
 * @param { types.Message[] } history - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const SearchImages = async (
  message: string,
  history: types.Message[],
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.SearchImages(
    message,
    history,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "SearchVideos" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } message - Input parameter.
 * @param { types.Message[] } history - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const SearchVideos = async (
  message: string,
  history: types.Message[],
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.SearchVideos(
    message,
    history,
  );
  return Promise.resolve(stream.toStreamable());
};