/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CurriculumData,  CurriculumRow,  DynamicFields,  ImageResult,  Message,  PdfKnowledge,  Resume,  VideoResult,  WebSearchResult,  WebSearchTool } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CurriculumData {
      rows: CurriculumRow[]
    }
    export interface CurriculumRow {
      grado?: string | null
      periodo?: string | null
      area?: string | null
      contenidos_tematicos?: string | null
      evidencias_del_dba?: string | null
      estandar_basico_competencia?: string | null
      indicador_desempeno?: string | null
    }
    export interface DynamicFields {
      [key: string]: any;
    }
    export interface ImageResult {
      img_src?: string | null
      url?: string | null
      title?: string | null
    }
    export interface Message {
      role?: string | null
      content?: string | null
    }
    export interface PdfKnowledge {
      title?: string | null
      content?: string | null
      competencias: string[]
      estandares: string[]
    }
    export interface Resume {
      markdown?: string | null
    }
    export interface VideoResult {
      img_src?: string | null
      url?: string | null
      title?: string | null
      iframe_src?: string | null
    }
    export interface WebSearchResult {
      title?: string | null
      url?: string | null
      img_src?: string | null
      iframe_src?: string | null
    }
    export interface WebSearchTool {
      query?: string | null
      engines: string[]
    }
}