/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    CurriculumData: ClassViewer<'CurriculumData', "rows">;
    
    CurriculumRow: ClassViewer<'CurriculumRow', "grado" | "periodo" | "area" | "contenidos_tematicos" | "evidencias_del_dba" | "estandar_basico_competencia" | "indicador_desempeno">;
    
    DynamicFields: ClassBuilder<'DynamicFields'>;
    
    ImageResult: ClassViewer<'ImageResult', "img_src" | "url" | "title">;
    
    Message: ClassViewer<'Message', "role" | "content">;
    
    PdfKnowledge: ClassViewer<'PdfKnowledge', "title" | "content" | "competencias" | "estandares">;
    
    Resume: ClassViewer<'Resume', "markdown">;
    
    VideoResult: ClassViewer<'VideoResult', "img_src" | "url" | "title" | "iframe_src">;
    
    WebSearchResult: ClassViewer<'WebSearchResult', "title" | "url" | "img_src" | "iframe_src">;
    
    WebSearchTool: ClassViewer<'WebSearchTool', "query" | "engines">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "CurriculumData","CurriculumRow","DynamicFields","ImageResult","Message","PdfKnowledge","Resume","VideoResult","WebSearchResult","WebSearchTool",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.CurriculumData = this.tb.classViewer("CurriculumData", [
          "rows",
        ]);
        
        this.CurriculumRow = this.tb.classViewer("CurriculumRow", [
          "grado","periodo","area","contenidos_tematicos","evidencias_del_dba","estandar_basico_competencia","indicador_desempeno",
        ]);
        
        this.DynamicFields = this.tb.classBuilder("DynamicFields", [
          
        ]);
        
        this.ImageResult = this.tb.classViewer("ImageResult", [
          "img_src","url","title",
        ]);
        
        this.Message = this.tb.classViewer("Message", [
          "role","content",
        ]);
        
        this.PdfKnowledge = this.tb.classViewer("PdfKnowledge", [
          "title","content","competencias","estandares",
        ]);
        
        this.Resume = this.tb.classViewer("Resume", [
          "markdown",
        ]);
        
        this.VideoResult = this.tb.classViewer("VideoResult", [
          "img_src","url","title","iframe_src",
        ]);
        
        this.WebSearchResult = this.tb.classViewer("WebSearchResult", [
          "title","url","img_src","iframe_src",
        ]);
        
        this.WebSearchTool = this.tb.classViewer("WebSearchTool", [
          "query","engines",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
         this.DynamicFields.reset(); 
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}